spring.application.name=smart-campus-hub

# MongoDB Atlas
spring.mongodb.uri=mongodb+srv://linwick679_db_user:MrRobot@cluster0.j8vuehp.mongodb.net/smart_campus_hub
spring.mongodb.database=smart_campus_hub

# Server
server.port=8081
