spring.application.name=smart-campus-hub

# MongoDB Atlas
spring.mongodb.uri=${MONGO_URI}
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.mongodb.database=smart_campus_hub

# Server
server.port=8080
