spring.application.name=smart-campus-hub

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://yenuligarusingarachchi_db_user:E6nGshEJfMHkUqf2@cluster0.j8vuehp.mongodb.net/smart_campus_hub
spring.data.mongodb.database=smart_campus_hub

# Server
server.port=8080
